project:
  type: book

book:
  title: "Expression Profiling of Differentially Expressed Genes Under Stress Conditions and FLC1 Modulation in *Cryptococcus neoformans*"
  author: 
    - name: "Diego Cesar Villa Almeyda"
      affiliations:
        - name: "The University of Edinburgh"
          department: "School of Mathematics"
  date: "01 July 2025"
  date-format: "MMMM, YYYY"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
    - references.qmd
    - appendix.qmd
  

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header:
      text: |
       \usepackage[font=small, labelfont={bf,small}, format=plain]{caption}
    template-partials:
      - before-body.tex
    papersize: a4
    geometry: top=2.5cm, bottom=2.5cm, left=3cm, right=3cm
    
number-sections: true

csl: vancouver.csl

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure


