project:
  type: book

book:
  title: "gene-expression"
  author: "Diego Cesar Villa Almeyda"
  date: "6/21/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
    - references.qmd
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
       \usepackage[font=small, labelfont={bf,small}, format=plain]{caption}
    
number-sections: true

csl: vancouver.csl

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure


